doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'App\Shared\Database\Migration': '%kernel.project_dir%/src/Shared/Database/Migration'
    enable_profiler: false
